kind: PersistentVolume
metadata:
  name: wp-disk
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: wp-disk
    fsType: ext4
---
kind: PersistentVolumeClaim
metadata:
  name: wp-disk-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
